name: Elixir CI

env:
  MIX_ENV: dev

on:
  push:

jobs:
  build:
    name: Run CI
    runs-on: ubuntu-20.04

    container:
      image: elixir:1.12.2-slim

    services:
      postgres:
        image: postgres:12.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432/tcp

    steps:
    - uses: actions/checkout@v2

    # - name: Download elixir
    #   run: wget https://packages.erlang-solutions.com/erlang/debian/pool/elixir_1.12.2-1~ubuntu~focal_all.deb

    # - name: Download elixir
    #   run: sudo dpkg -i elixir_1.12.2-1~ubuntu~focal_all.deb

    - name: Install hex
      run: mix local.hex --force

    - name: Install rebar
      run: mix local.rebar --force

    - name: Build dependencies
      run: mix deps.get && mix compile

    - name: Code scan
      run: mix sobelow --config

    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

    - name: Credo
      run: mix credo

    - name: Unit tests
      run: mix test
      env:
        DATABASE_URL: postgres
        DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
